### ISSUE TITLE
不能上传html-webpack-plugin生成的html文件

### ISSUE THREAD

**Issue by taoyingsong** [fisherw/webpack-upload#1]

**Comment by fisherw** [comment]
目前是不支持上传html文件的，在webpack它不属于编译output的内容。而且你为什么要支持上传Html,什么场景下需要把html也传上去？

**Comment by daiyamin** [comment]
这个最好不要限制死吧，最好可以自定义上传哪些打包出的文件

**Comment by jasonjin-ai** [comment]
当然需要上传html文件啊，上传到远程开发机，进行整体测试，这种场景就不行，之前还是可以的，不想换插件来回折腾，最好改写一下
