### ISSUE TITLE
可以扩展下吗，现在有个场景并不需要把所有打包的文件上传，只上传一部分？

### ISSUE THREAD

**Issue by daiyamin** [fisherw/webpack-upload#2]

**Comment by fisherw** [comment]
按理说编译后除了html，其它静态资源是都可以cdn的。如果有这样的需求我在后续版本支持一下定义需要上传文件的类型。

**Comment by daiyamin** [comment]
是这样的，我现在想把sourcemap生成的map文件传到服务器上，其他的静态资源不上传，什么时候可以支持啊？

**Comment by fisherw** [comment]
今天支持，最迟下午发一个版上去。
