### ISSUE TITLE
使用webpack4的话，无法将html文件上传到指定目录

### ISSUE THREAD

**Issue by jasonjin-ai** [fisherw/webpack-upload#3]
使用webpack4的话，无法将html文件上传到指定目录

**Comment by jasonjin-ai** [comment]
算了，我自己改了，将html想干部分注释掉就好了

**Comment by fisherw** [comment]
一般情况是不需要将html上传到cdn的，如果你有这个要求，可以写test过滤条件，这个插件支持个性化定制上传哪些资源的。
